accounts/urls.py
from django.urls import path

from . import views

#app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignupPageView.as_view(), name='signup'),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='list'),
    path('<uuid:pk>', views.BookDetailView.as_view(), name='detail'),
    path('search/', views.SearchResultsListView.as_view(), name='search_results'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Django admin
    path('anything-but-admin-lol/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # Project apps
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
    path('books/', include('books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    

pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.HomepageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

books/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse


class Book(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to='covers', blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['id'], name='id_index'),
        ]
        permissions = [
            ('special_status', 'Can read all books'),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:detail', args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='reviews',
    )
    review = models.CharField(max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.review

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

CustomUser = get_user_model()


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm


class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.views.generic import DetailView, ListView

from .models import Book


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    # context_object_name = 'book_list' # Not required as using default object name
    # template_name = 'books/book_list.html' # Not required as using default template name
    login_url = 'account_login'


class BookDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Book
    # context_object_name = 'book'
    # template_name = 'books/book_detail.html'
    login_url = 'account_login'
    permission_required = 'books.special_status'


class SearchResultsListView(ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'books/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Book.objects.filter(
            Q(title__icontains=query) | 
            Q(author__icontains=query)
        )

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = 'home.html'


class AboutPageView(TemplateView):
    template_name = 'about.html'

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
<h1>About Page</h1>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bookstore{% endblock title %}</title>
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
    <header>{% include 'navbar.html' %}</header>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <!-- JavaScript -->
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
        integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/base.js' %}"></script>
</body>

</html>

templates/books/book_detail.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock title %}

{% block content %}
<div class="book-detail">
    {% if book.cover %}
    <img class="bookcover" src="{{ book.cover.url}}" alt="{{ book.title }}">
    {% endif %}
    <h2><a href="">{{ book.title }}</a></h2>
    <p>Author: {{ book.author }}</p>
    <p>Price: {{ book.price }}</p>
    <div>
        <h3>Reviews</h3>
        <ul>
            {% for review in book.reviews.all %}
            <li>{{ review.review }} ({{ review.author }})</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

templates/books/book_list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock title %}

{% block content %}
  {% for book in book_list %}
    <div>
      <h2><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h2>
    </div>
  {% endfor %}
{% endblock content %}

templates/books/search_results.html
{% extends 'base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}
  <h1>Search Results</h1>
  {% for book in book_list %}
    <div>
      <h3><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h3>
      <p>Author: {{ book.author }}</p>
      <p>Price: $ {{ book.price }}</p>
    </div>
  {% endfor %}
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}

<h1>Homepage</h1>
<form class="form-inline mt-2 mt-md-0" action="{% url 'books:search_results' %}" method="get">
    <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
</form>
{% endblock content %}

templates/navbar.html
<!-- Fixed navbar -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
mb-3 bg-white border-bottom shadow-sm">
  <a href="{% url 'pages:home' %}" class="navbar-brand my-0 mr-md-auto
 font-weight-normal">Bookstore</a>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="{% url 'books:list' %}">Books</a>
    <a class="p-2 text-dark" href="{% url 'pages:about' %}">About</a>
    {% if user.is_authenticated %}
    <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
    <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
    {% endif %}
  </nav>
</div>